// <auto-generated />
using System;
using ChazuraProgram.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChazuraProgram.Migrations
{
    [DbContext(typeof(ChazuraContext))]
    [Migration("20201013022627_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChazuraProgrem.Models.DafimShas", b =>
                {
                    b.Property<string>("DafID")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("DafHebraw")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("DafNumber")
                        .HasColumnType("int");

                    b.Property<string>("MeshactaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("TwoSided")
                        .HasColumnType("bit");

                    b.HasKey("DafID");

                    b.HasIndex("MeshactaID");

                    b.ToTable("DafimShas");
                });

            modelBuilder.Entity("ChazuraProgrem.Models.MeshctaShas", b =>
                {
                    b.Property<string>("MeshactaID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("MeshachtaEngName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("MeshactaHebrawName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("StartsAtDaf")
                        .HasColumnType("int");

                    b.Property<int>("TotolDafim")
                        .HasColumnType("int");

                    b.HasKey("MeshactaID");

                    b.ToTable("MeshctaShas");
                });

            modelBuilder.Entity("ChazuraProgrem.Models.ShasChazuraData", b =>
                {
                    b.Property<int>("ChartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChazuraTimes")
                        .HasColumnType("int");

                    b.Property<string>("DafID")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeshactaID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ChartId");

                    b.HasIndex("DafID");

                    b.HasIndex("MeshactaID");

                    b.ToTable("ShasChazuraData");
                });

            modelBuilder.Entity("ChazuraProgrem.Models.DafimShas", b =>
                {
                    b.HasOne("ChazuraProgrem.Models.MeshctaShas", "Meshacta")
                        .WithMany("ShasDafim")
                        .HasForeignKey("MeshactaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChazuraProgrem.Models.ShasChazuraData", b =>
                {
                    b.HasOne("ChazuraProgrem.Models.DafimShas", "Daf")
                        .WithMany("ChazuraCharts")
                        .HasForeignKey("DafID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChazuraProgrem.Models.MeshctaShas", "Meshacta")
                        .WithMany("ChazuraCharts")
                        .HasForeignKey("MeshactaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
